### ISSUE TITLE
Detected package version outside of dependency constraint: (Automapper 12)

### ISSUE THREAD

**Issue by mubeda** [AutoMapper/AutoMapper.Extensions.EnumMapping#17]
Hi there!
Today i upgraded to Automapper 12 and  i started to get this warnings.

Detected package version outside of dependency constraint: AutoMapper.Extensions.EnumMapping 2.0.1 requires AutoMapper (>= 11.0.0 && < 12.0.0) but version AutoMapper 12.0.0 was resolved.

**Comment by odinnou** [comment]
Hello, thanks for your job with this extension!

Same issue here ^^

**Comment by HenkKin** [comment]
Maybe time to create a new release?

**Comment by ioaznnis** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.

**Comment by vadimkhm** [comment]
Waiting for the new release. Thanks!

**Comment by jbogard** [comment]
Released!

**Comment by mubeda** [comment]
Thank you so much!

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Jimmy Bogard ***@***.***>
Enviado: Friday, October 7, 2022 3:53:07 PM
Para: AutoMapper/AutoMapper.Extensions.EnumMapping ***@***.***>
Cc: mubeda ***@***.***>; Author ***@***.***>
Asunto: Re: [AutoMapper/AutoMapper.Extensions.EnumMapping] Detected package version outside of dependency constraint: (Automapper 12) (Issue #17)


Released!
