### ISSUE TITLE
Use of the EnableEnumMappingValidation throws NullReferenceException

### ISSUE THREAD

**Issue by trejjam** [AutoMapper/AutoMapper.Extensions.EnumMapping#18]
### Mapping configuration

```csharp
new MapperConfiguration(c =>
{
  c.EnableEnumMappingValidation();
  c.CreateMap<object, object>();
})
```

### Expected behavior

It validates mapping and does not throw exception 

### Actual behavior

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at AutoMapper.Features.Features`1.GetEnumerator()
   at AutoMapper.Extensions.EnumMapping.EnumMapperConfigurationExpressionExtensions.<>c.<EnableEnumMappingValidation>b__0_0(ValidationContext context)
   at AutoMapper.Configuration.ConfigurationValidator.Validate(ValidationContext context)
   at AutoMapper.Configuration.ConfigurationValidator.DryRunTypeMap(IGlobalConfiguration config, HashSet`1 typeMapsChecked, TypePair types, TypeMap typeMap, MemberMap memberMap)
   at AutoMapper.Configuration.ConfigurationValidator.AssertConfigurationIsValid(IGlobalConfiguration config, IEnumerable`1 typeMaps)
```

### Steps to reproduce

```csharp
new MapperConfiguration(c =>
{
  c.EnableEnumMappingValidation();
  c.CreateMap<object, object>();
}).AssertConfigurationIsValid();
```

**Comment by lbargaoanu** [comment]
A PR is welcome.

**Comment by HenkKin** [comment]
I found the issue, tomorrow I hope to offer a pull request

**Comment by lbargaoanu** [comment]
The fix is in this repo, replace the `foreach` with `Get<TFeature>()`. Enumeration is for internal use.

**Comment by trejjam** [comment]
I tried to use the `context.TypeMap.Features.Get<IEnumMappingValidationRuntimeFeature>()`. The issue is that `Get` search by `GetType` of searched items, which is the `EnumMappingValidationRuntimeFeature<TSource, TDestination>`. And in the `Features.Get<IEnumMappingValidationRuntimeFeature>()` context you do not have `TSource, TDestination`.

There are several ways how to solve it.
a) Create proxy class `EnumMappingValidationRuntimeFeature` which can be called without `TSource, TDestination`:
```cs
internal class EnumMappingValidationRuntimeFeature : IEnumMappingValidationRuntimeFeature
{
private readonly IEnumMappingValidationRuntimeFeature  _innerValidationRuntimeFeature;
public EnumMappingValidationRuntimeFeature(IEnumMappingValidationRuntimeFeature innerValidationRuntimeFeature)
{
  _innerValidationRuntimeFeature = innerValidationRuntimeFeature;
}

void IEnumMappingValidationRuntimeFeature.Validate(TypePair typePair) => _innerValidationRuntimeFeature.Validate(typePair);
}
```

b) Add `GetAssignableTo<T>` into the `Features<TFeature>`.
c) use reglection and call `Get<EnumMappingValidationRuntimeFeature<TSource, TDestination>>()`

Which one do you like?

**Comment by trejjam** [comment]
I created PR with the first option

**Comment by adamhathcock** [comment]
Is there a workaround or does the PR need merging?  I can't tell if I'm doing something wrong or not

**Comment by trejjam** [comment]
Hello Adam, as you can see there is an issue and there is also a PR. What do you think?

**Comment by adamhathcock** [comment]
I think you're being a jerk when I was asking the question if there was a workaround or is it just completely broken.

I appreciate you doing the PR though.

**Comment by HenkKin** [comment]
Released!
