### ISSUE TITLE
Nuget Package Missing

### ISSUE THREAD

**Issue by napoleonjones** [AutoMapper/AutoMapper.Extensions.EnumMapping#2]
The linked Nuget Package does not exist.

**Comment by jbogard** [comment]
@HenkKin anything I need to do on my side?

**Comment by HenkKin** [comment]
That's true, it is waiting for next AutoMapper version after version 9.0.0

**Comment by HenkKin** [comment]
> @HenkKin anything I need to do on my side?

When do you expect the next version of AutoMapper?

**Comment by HenkKin** [comment]
@jbogard When do you expect the next version of AutoMapper?

**Comment by robbaman** [comment]
I was led here via the docs. If this feature is awaiting a version later than 9, is there any update as to the release date of this next version? @jbogard 

Also. I assume then that the code for this version doesn't work with the current AutoMapper version? We regularly map enums and it'd be great to have validation throw errors when one of the two has a new value added that the destination enum doesn't have. 

Should the next version of AutoMapper be a long way out, is there a way to get this validation to work with the current AutoMapper version?

**Comment by lbargaoanu** [comment]
Meanwhile, https://myget.org/feed/automapperdev/package/nuget/AutoMapper.Extensions.EnumMapping.

**Comment by robbaman** [comment]
> Meanwhile, https://myget.org/feed/automapperdev/package/nuget/AutoMapper.Extensions.EnumMapping.

Thanks. Finally found some time to look into this and the version on MyGet does exactly what I want. Question now remains if there's any indication as to when we can expect this new version of AutoMapper that is apparently required to get this to work.

@jbogard or @HenkKin is there any ETA in sight? I'd prefer not to release software that's based on a MyGet preview version. If you're busy and it's a long way out still It'd be great to know as well :)

**Comment by fbridger** [comment]
Any idea when this package is going to be available again?

**Comment by DevsAnon** [comment]
So, would this nuget package be available?

**Comment by robbaman** [comment]
I noticed AutoMapper version 10.0.0.0 has released, does this mean this package will be published to public NuGet soon as well?

**Comment by HenkKin** [comment]
> @HenkKin anything I need to do on my side?

@jbogard could you create the nuget packages for AutoMapper.Extensions.EnumMapping

**Comment by jbogard** [comment]
I'll get this package updated today (and moved to GH actions)
