### ISSUE TITLE
Support projection (ProjectTo) by fixing CustomMapExpressionFactory

### ISSUE THREAD

**Issue by Xriuk** [AutoMapper/AutoMapper.Extensions.EnumMapping#20]
https://github.com/AutoMapper/AutoMapper.Extensions.EnumMapping/blob/9b8cbcb4352f3370c28fc24251c5a6cd2ccbc31b/src/AutoMapper.Extensions.EnumMapping/Internal/CustomMapExpressionFactory.cs#L18

Maybe it's possible to remove the `ResolutionContext` parameter (and maybe destination too?) since it's not even used (I don't know exactly how AutoMapper works under the hood)? Maybe this would allow projections to work?

**Comment by lbargaoanu** [comment]
A PR is welcome.
