### ISSUE TITLE
Release needed for compatibility with AutoMapper 13.0.0

### ISSUE THREAD

**Issue by KirkMunroSagent** [AutoMapper/AutoMapper.Extensions.EnumMapping#24]
Now that you've released AutoMapper 13.0.0, projects using both that and AutoMapper.Extensions.EnumMapping cannot update to the latest version of AutoMapper because AutoMapper.Extensions.EnumMapping 3.1.0 requires AutoMapper (>= 12.0.0 && < 13.0.0). Please publish an update of AutoMapper.Extensions.EnumMapping that is compatible with AutoMapper 13.0.0. Thanks!

**Comment by HenkKin** [comment]
I will update it

**Comment by HenkKin** [comment]
@KirkMunroSagent new version is available: https://www.nuget.org/packages/AutoMapper.Extensions.EnumMapping/3.2.0
