### ISSUE TITLE
Enable opt-in to case-insensitive mapping of enums

### ISSUE THREAD

**Issue by earloc** [AutoMapper/AutoMapper.Extensions.EnumMapping#7]
In vanilla AM, with the default behavior of [EnumToEnumMapper](https://github.com/AutoMapper/AutoMapper/blob/master/src/AutoMapper/Mappers/EnumToEnumMapper.cs), we have a mechanism in place that gracefully handles situations where differences in the naming of enum-values ar present.

For instance, mapping between these two enums is a no brainer:

```
public enum Source {
   bar,
   foo,
   foobar
}

public enum Destination {
   FOO,
   FooBar,
   BAR
}
```

However, when we leverage customization of mappings, we completely loose this convenience, when all we need is to customize a single or a few couple of enum-values.

Proposal:
Extend IEnumConfigurationExpression.MapByName to take an optional boolean parameter to control the internal behavior.
Default value would be false, as this should be the most back-wards-compatible introduction for this.

`IEnumConfigurationExpression<TSource, TDestination> MapByName(bool ignoreCase = false);`

**Comment by earloc** [comment]
@HenkKin and/or @jbogard 
does this make sense?

Noticed that https://github.com/AutoMapper/AutoMapper/issues/3562 seemed to be connected, but the discussion there suddenly vanished o_O

**Comment by earloc** [comment]
Hey folks.
Any thoughts on this?

Is this repo even interrested in contributions?

**Comment by HenkKin** [comment]
To extend MapByName with an optional ignoreCase seems ok to me. Otherwise you have to explicitly define the enum value mappings for just different casings.

**Comment by HenkKin** [comment]
To extend MapByName with an optional ignoreCase seems ok to me. Otherwise you have to explicitly define the enum value mappings for just different casings.

See my review of the pull request https://github.com/AutoMapper/AutoMapper.Extensions.EnumMapping/pull/9.

**Comment by earloc** [comment]
Ok, just adopted your suggestions.

![image](https://user-images.githubusercontent.com/8486862/108003787-14681180-6ff4-11eb-8eef-396fc13328d2.png)

**Comment by earloc** [comment]
Any plans when this find's it's way into NuGet?
And when should we close this issue? After release?

**Comment by HenkKin** [comment]
@jbogard can I create a new release?

**Comment by earloc** [comment]
Yeah @jbogard, can he?

**Comment by HenkKin** [comment]
@earloc new version of package is released
